package com.sih.dataservice.dossier.service;

import com.sih.dataservice.audit.service.AuditService;
import com.sih.dataservice.auth.model.UserPrincipal;
import com.sih.dataservice.complaints.dto.CaseEventDto;
import com.sih.dataservice.complaints.dto.ComplaintAccountDto;
import com.sih.dataservice.complaints.dto.EvidenceDto;
import com.sih.dataservice.complaints.dto.IncidentDetailDto;
import com.sih.dataservice.complaints.service.ComplaintService;
import com.sih.dataservice.dossier.dto.IncidentDossierDto;
import com.sih.dataservice.ml.dto.PredictionDto;
import com.sih.dataservice.ml.entity.Prediction;
import com.sih.dataservice.ml.repository.PredictionRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Clock;
import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

@Service
public class DossierService {

    private final ComplaintService complaintService;
    private final PredictionRepository predictionRepository;
    private final AuditService auditService;
    private final Clock clock;

    public DossierService(ComplaintService complaintService,
                          PredictionRepository predictionRepository,
                          AuditService auditService,
                          Clock clock) {
        this.complaintService = complaintService;
        this.predictionRepository = predictionRepository;
        this.auditService = auditService;
        this.clock = clock;
    }

    @Transactional
    public IncidentDossierDto getDossier(UUID incidentId, UserPrincipal principal, String clientIp) {
        // Enforce scope and load incident
        IncidentDetailDto detail = complaintService.getIncidentDetail(incidentId, principal);

        Optional<Prediction> predictionOpt = predictionRepository
                .findTopByComplaintIdOrderByCreatedAtDesc(incidentId);
        PredictionDto predictionDto = predictionOpt.map(PredictionDto::fromEntity).orElse(null);

        auditService.log(principal.getId(), principal.getRole().name(), "EXPORT_DOSSIER", "COMPLAINT",
                incidentId.toString(), "{\"format\":\"JSON\"}", clientIp);

        return new IncidentDossierDto(
                detail,
                predictionDto,
                Instant.now(clock),
                principal.getUsername(),
                "CONFIDENTIAL - LAW ENFORCEMENT & REGULATORY SENSITIVE"
        );
    }

    @Transactional
    public String exportMarkdown(UUID incidentId, UserPrincipal principal, String clientIp) {
        IncidentDossierDto dossier = getDossier(incidentId, principal, clientIp);
        IncidentDetailDto inc = dossier.getIncident();

        StringBuilder sb = new StringBuilder();
        sb.append("# Incident Dossier: ").append(inc.getHumanReference()).append("\n\n");
        sb.append("**Classification:** ").append(dossier.getClassificationNotice()).append("\n\n");
        sb.append("- **Incident ID:** ").append(inc.getId()).append("\n");
        sb.append("- **Status:** ").append(inc.getStatus()).append("\n");
        sb.append("- **Fraud Type:** ").append(inc.getFraudType()).append("\n");
        sb.append("- **Amount:** ₹").append(inc.getAmount()).append("\n");
        sb.append("- **Incident Time:** ").append(inc.getIncidentTime()).append("\n");
        sb.append("- **Jurisdiction:** ").append(inc.getJurisdictionName() != null ? inc.getJurisdictionName() : "N/A").append("\n");
        sb.append("- **Generated By:** ").append(dossier.getGeneratedBy()).append(" at ").append(dossier.getGeneratedAt()).append("\n\n");

        sb.append("## Description\n");
        sb.append(inc.getDescriptionOriginal() != null ? inc.getDescriptionOriginal() : "No description provided.").append("\n\n");

        sb.append("## Risk & ML Assessment\n");
        if (dossier.getPrediction() != null) {
            PredictionDto p = dossier.getPrediction();
            sb.append("- **Risk Score:** ").append(p.getRisk()).append("\n");
            sb.append("- **Confidence:** ").append(p.getConfidence()).append("\n");
            sb.append("- **Model Version:** ").append(p.getModelVersion()).append("\n");
            sb.append("- **Model Available:** ").append(p.isModelAvailable()).append("\n");
            sb.append("- **Explanation:** ").append(p.getExplanation()).append("\n\n");
        } else {
            sb.append("_No ML predictions recorded for this incident yet._\n\n");
        }

        sb.append("## Involved Accounts\n");
        if (inc.getAccounts() != null && !inc.getAccounts().isEmpty()) {
            sb.append("| Account (Encrypted/Masked) | Bank | Entity Type | Role |\n");
            sb.append("|---|---|---|---|\n");
            for (ComplaintAccountDto acc : inc.getAccounts()) {
                sb.append("| ").append(acc.getAccountHash() != null ? "[PROTECTED: " + acc.getAccountHash().substring(0, Math.min(8, acc.getAccountHash().length())) + "...]" : "N/A")
                        .append(" | ").append(acc.getBankName() != null ? acc.getBankName() : "N/A")
                        .append(" | ").append(acc.getEntityType())
                        .append(" | ").append(acc.getRole()).append(" |\n");
            }
            sb.append("\n");
        } else {
            sb.append("_No accounts recorded._\n\n");
        }

        sb.append("## Case Timeline\n");
        if (inc.getEvents() != null && !inc.getEvents().isEmpty()) {
            sb.append("| Timestamp | Actor | From Status | To Status | Remarks |\n");
            sb.append("|---|---|---|---|---|\n");
            for (CaseEventDto ev : inc.getEvents()) {
                sb.append("| ").append(ev.getCreatedAt())
                        .append(" | ").append(ev.getActorName() != null ? ev.getActorName() : "SYSTEM")
                        .append(" | ").append(ev.getFromStatus() != null ? ev.getFromStatus() : "-")
                        .append(" | ").append(ev.getToStatus())
                        .append(" | ").append(ev.getNote() != null ? ev.getNote().replace("|", "/") : "").append(" |\n");
            }
            sb.append("\n");
        } else {
            sb.append("_No case events recorded._\n\n");
        }

        sb.append("## Stored Evidence\n");
        if (inc.getEvidence() != null && !inc.getEvidence().isEmpty()) {
            sb.append("| Filename | Content Type | Size (Bytes) | SHA-256 Hash |\n");
            sb.append("|---|---|---|---|\n");
            for (EvidenceDto ev : inc.getEvidence()) {
                sb.append("| ").append(ev.getFilePath())
                        .append(" | ").append(ev.getMimeType())
                        .append(" | ").append(ev.getSizeBytes())
                        .append(" | ").append(ev.getSha256()).append(" |\n");
            }
            sb.append("\n");
        } else {
            sb.append("_No evidence files attached._\n\n");
        }

        return sb.toString();
    }

    @Transactional(readOnly = true)
    public String exportHtml(UUID incidentId, UserPrincipal principal, String clientIp) {
        IncidentDossierDto dossier = getDossier(incidentId, principal, clientIp);
        IncidentDetailDto inc = dossier.getIncident();

        StringBuilder sb = new StringBuilder();
        sb.append("<!DOCTYPE html><html><head><meta charset=\"UTF-8\">");
        sb.append("<title>Incident Dossier - ").append(inc.getHumanReference()).append("</title>");
        sb.append("<style>");
        sb.append("body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; color: #1e293b; line-height: 1.6; }");
        sb.append(".header { border-bottom: 2px solid #0284c7; padding-bottom: 16px; margin-bottom: 24px; }");
        sb.append(".badge { display: inline-block; padding: 4px 10px; border-radius: 4px; font-weight: 600; font-size: 0.85rem; }");
        sb.append(".badge-conf { background: #fee2e2; color: #991b1b; }");
        sb.append(".badge-risk { background: #fef3c7; color: #92400e; font-size: 1rem; }");
        sb.append("table { width: 100%; border-collapse: collapse; margin-top: 12px; margin-bottom: 24px; }");
        sb.append("th, td { border: 1px solid #cbd5e1; padding: 10px; text-align: left; }");
        sb.append("th { background-color: #f8fafc; font-weight: 600; }");
        sb.append("h2 { color: #0f172a; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; margin-top: 32px; }");
        sb.append("</style></head><body>");

        sb.append("<div class=\"header\">");
        sb.append("<span class=\"badge badge-conf\">").append(dossier.getClassificationNotice()).append("</span>");
        sb.append("<h1>Incident Dossier: ").append(inc.getHumanReference()).append("</h1>");
        sb.append("<p>Generated by <strong>").append(dossier.getGeneratedBy()).append("</strong> on ").append(dossier.getGeneratedAt()).append("</p>");
        sb.append("</div>");

        sb.append("<h2>Incident Summary</h2>");
        sb.append("<table>");
        sb.append("<tr><th>Incident ID</th><td>").append(inc.getId()).append("</td><th>Status</th><td>").append(inc.getStatus()).append("</td></tr>");
        sb.append("<tr><th>Fraud Type</th><td>").append(inc.getFraudType()).append("</td><th>Amount</th><td>₹").append(inc.getAmount()).append("</td></tr>");
        sb.append("<tr><th>Incident Time</th><td>").append(inc.getIncidentTime()).append("</td><th>Jurisdiction</th><td>").append(inc.getJurisdictionName() != null ? inc.getJurisdictionName() : "N/A").append("</td></tr>");
        sb.append("</table>");

        sb.append("<h2>Risk & ML Inference</h2>");
        if (dossier.getPrediction() != null) {
            PredictionDto p = dossier.getPrediction();
            sb.append("<p><span class=\"badge badge-risk\">Risk Score: ").append(p.getRisk()).append("</span> (Confidence: ").append(p.getConfidence()).append(")</p>");
            sb.append("<p><strong>Model Version:</strong> ").append(p.getModelVersion()).append(" | <strong>Model Available:</strong> ").append(p.isModelAvailable()).append("</p>");
            sb.append("<pre style=\"background: #f1f5f9; padding: 12px; border-radius: 6px; overflow-x: auto;\">").append(p.getExplanation()).append("</pre>");
        } else {
            sb.append("<p><em>No ML predictions recorded for this incident.</em></p>");
        }

        sb.append("<h2>Involved Accounts</h2>");
        if (inc.getAccounts() != null && !inc.getAccounts().isEmpty()) {
            sb.append("<table><tr><th>Account Hash</th><th>Bank</th><th>Entity Type</th><th>Role</th></tr>");
            for (ComplaintAccountDto acc : inc.getAccounts()) {
                sb.append("<tr><td>").append(acc.getAccountHash())
                        .append("</td><td>").append(acc.getBankName() != null ? acc.getBankName() : "N/A")
                        .append("</td><td>").append(acc.getEntityType())
                        .append("</td><td>").append(acc.getRole()).append("</td></tr>");
            }
            sb.append("</table>");
        } else {
            sb.append("<p><em>No accounts recorded.</em></p>");
        }

        sb.append("<h2>Timeline & Case Events</h2>");
        if (inc.getEvents() != null && !inc.getEvents().isEmpty()) {
            sb.append("<table><tr><th>Timestamp</th><th>Actor</th><th>From</th><th>To</th><th>Remarks</th></tr>");
            for (CaseEventDto ev : inc.getEvents()) {
                sb.append("<tr><td>").append(ev.getCreatedAt())
                        .append("</td><td>").append(ev.getActorName() != null ? ev.getActorName() : "SYSTEM")
                        .append("</td><td>").append(ev.getFromStatus() != null ? ev.getFromStatus() : "-")
                        .append("</td><td>").append(ev.getToStatus())
                        .append("</td><td>").append(ev.getNote() != null ? ev.getNote() : "").append("</td></tr>");
            }
            sb.append("</table>");
        } else {
            sb.append("<p><em>No case events recorded.</em></p>");
        }

        sb.append("<h2>Evidence Chain of Custody</h2>");
        if (inc.getEvidence() != null && !inc.getEvidence().isEmpty()) {
            sb.append("<table><tr><th>Filename</th><th>Content Type</th><th>Size (Bytes)</th><th>SHA-256 Hash</th></tr>");
            for (EvidenceDto ev : inc.getEvidence()) {
                sb.append("<tr><td>").append(ev.getFilePath())
                        .append("</td><td>").append(ev.getMimeType())
                        .append("</td><td>").append(ev.getSizeBytes())
                        .append("</td><td><code>").append(ev.getSha256()).append("</code></td></tr>");
            }
            sb.append("</table>");
        } else {
            sb.append("<p><em>No evidence attached.</em></p>");
        }

        sb.append("</body></html>");
        return sb.toString();
    }
}
